### ISSUE TITLE
Error console when importing any

### ISSUE THREAD

**Issue by dschense** [bandantonio/obsidian-apple-books-highlights-plugin#15]
**Description the bug**
The plugin is not working. not with the commands, not with the icon in sidebar.
getting this error in console output:

```
Error importing Apple Books highlights: SyntaxError: Unexpected end of JSON input
eval @ plugin:apple-books-import-highlights:6154
Promise.catch (async)
eval @ plugin:apple-books-import-highlights:6152
```

Also include the following details:
- Error behavior: intermittent/permanent.
- Error occurs when:
  - [x] Importing a single book
  - [x] Importing all books
  - [x] All the above
- Number of books and highlights (approximately)

**General information**
- Plugin version: 1.2.1
- Obsidian version: 1.5.12
- MacOS version: Sonoma 14.4.1

**To Reproduce**
- option+command --> Apple Books import command
- with icon in sidebar

**Expected behavior**
importing some highlights

**Screenshots**
no screeny - error text 

**Additional context**
getting this error in console:

**Comment by JeminiRiver** [comment]
Getting the same issue. Same error, same line number. This seems to be happening because the query in `getAnnotations()`

`SELECT ZANNOTATIONASSETID, ZFUTUREPROOFING5, ZANNOTATIONREPRESENTATIVETEXT, ZANNOTATIONSELECTEDTEXT, ZANNOTATIONNOTE, ZANNOTATIONCREATIONDATE, ZANNOTATIONMODIFICATIONDATE, ZANNOTATIONSTYLE
		FROM ZAEANNOTATION
		WHERE ZANNOTATIONSELECTEDTEXT IS NOT NULL
		AND ZANNOTATIONDELETED IS 0;
`

is returning 0 results. and causes the `JSON.parse(stdout)` to fail.

I confirmed I had no highlighted "Books", only "PDFs." Pulled out a random Book and added a highlight and the plugin worked as expected. I converted one of my PDFs to EPUB, added a highlight and it showed up in Obsidian when I reran the sync as well.

Little sad to see PDFs don't seem supported. Poking at the sqlite databases in question it seems like PDF annotations may be stored differently or elsewhere.

**Comment by bandantonio** [comment]
@dschense Thanks for the report
@JeminiRiver Thanks for the report and for the explanation of the error.

@dschense The error you're receiving is caused (as @JeminiRiver mentioned in her message) by an empty response after querying the database, which means that you probably have no books in your Apple Books application. Could you please confirm that?

> it seems like PDF annotations may be stored differently or elsewhere.

@JeminiRiver Yes, you're right. However, it's a bit tricky. Apple Books is a convenient place to store PDFs but the tricky thing is that even they're getting added to the library database, all the highlights are not stored in the database and seem to be added to the document itself. You can check the highlights using Preview, for example, via Highlights and Notes pane (Command + Option + 4). Converting PDF to ePub helps to workaround this, for sure. So, I believe it's more like lack of native support for highlights rather than the plugin's missing feature. But I will check the possibility of adding it anyway.

**Comment by dschense** [comment]
sorry for the late response:
there are a lot books in my library. They are all epubs or downloaded direktly from the apple store.
for me there is still the same error. 

Dont know what to do, to fix this.

**Comment by bandantonio** [comment]
@dschense Thanks for the information. I will definitely go deeper into the issue because now, I was able to reproduce your issue on an empty database only. I'm also planning to do a partial refactoring of the fetching logic and write tests, so it should also help to avoid that kind of issue in the future. Sorry for the inconvenience.

**Comment by dschense** [comment]
Thank you for your commitment @bandantonio

I have carried out a few more tests to definitely rule out an error on my part.
I'm pretty sure that it can't be my library. 

installed this Plugin for a test:
https://github.com/atfzl/obsidian-apple-books-plugin

With this plugin a sync to Obsidian works without any problems.
Maybe this information helps to find the bug.

**Comment by bandantonio** [comment]
@dschense Thank you too for your help, that will definitely come in handy.

**Comment by bandantonio** [comment]
Reopened as the issue still exists.
