### ISSUE TITLE
[Bug]: Highlights not listed in chronological order as expected. 

### ISSUE THREAD

**Issue by genremonk** [bandantonio/obsidian-apple-books-highlights-plugin#19]
The display of the highlights and notes appears to be shuffled. Not quite random, but not in sequential order; i.e. the order they appear in a book, resulting in confusion.

**Comment by bandantonio** [comment]
By default, highlights appear in the order you made them in the book (by creation date: from older to newer). For example, 

Phrase 1 (highlighted fourth)
Phrase 2 (highlighted first)
Phrase 3 (highlighted third)
Phrase 4 (highlighted second)

The plugin will list the highlights as follows:

Phrase 2 (highlighted first)
Phrase 4 (highlighted second)
Phrase 3 (highlighted third)
Phrase 1 (highlighted fourth)

So this is a feature, rather than a bug 😀

Closing this issue as ordering options (including the current one) will be implemented in the feature request #12 You may wanna subscribe to that request to stay updated with the progress.

**Comment by genremonk** [comment]
". . .  highlights appear in the order you made them in the book." 

I figured that this is the intended behavior, but it doesn't seem to be the case. I am annotating a book linearly (it's fiction, so I know I wouldn't be jumping around like I might in a text book), and yet, the highlights and associated notes do not appear in order upon import. Mostly in order, but some are out of sequence. Thanks for your attention.

**Comment by bandantonio** [comment]
@genremonk Thank you for the detailed reply. I need to check this behavior more closely.
